site_name: Python SDK
repo_url: https://github.com/Open-Pix/python-sdk
repo_name: Open-Pix/python-sdk
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/open-pix.png
  favicon: assets/icon.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/style.css